In [59]:
import pandas as pd
import numpy as np

df_hour = pd.read_csv('hour.csv')
display(df_hour)

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0000,3,13,16
1,2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0000,8,32,40
2,3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0000,5,27,32
3,4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0000,3,10,13
4,5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17374,17375,2012-12-31,1,1,12,19,0,1,1,2,0.26,0.2576,0.60,0.1642,11,108,119
17375,17376,2012-12-31,1,1,12,20,0,1,1,2,0.26,0.2576,0.60,0.1642,8,81,89
17376,17377,2012-12-31,1,1,12,21,0,1,1,1,0.26,0.2576,0.60,0.1642,7,83,90
17377,17378,2012-12-31,1,1,12,22,0,1,1,1,0.26,0.2727,0.56,0.1343,13,48,61
17378,17379,2012-12-31,1,1,12,23,0,1,1,1,0.26,0.2727,0.65,0.1343,12,37,49

In [60]:
#inspeção#

# caracteristica da base de dados

display(df_hour.shape)

(17379, 17)

In [61]:
#inspeção#



# caracteristica da base de dados - colunas

display(list(df_hour.columns))

['instant',
 'dteday',
 'season',
 'yr',
 'mnth',
 'hr',
 'holiday',
 'weekday',
 'workingday',
 'weathersit',
 'temp',
 'atemp',
 'hum',
 'windspeed',
 'casual',
 'registered',
 'cnt']

In [62]:
#inspeção#

# caracteristica da base de dados - descrições

display(df_hour.info())

<class 'pandas.DataFrame'>
RangeIndex: 17379 entries, 0 to 17378
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     17379 non-null  int64
 1   dteday      17379 non-null  str
 2   season      17379 non-null  int64
 3   yr          17379 non-null  int64
 4   mnth        17379 non-null  int64
 5   hr          17379 non-null  int64
 6   holiday     17379 non-null  int64
 7   weekday     17379 non-null  int64
 8   workingday  17379 non-null  int64
 9   weathersit  17379 non-null  int64
 10  temp        17379 non-null  float64
 11  atemp       17379 non-null  float64
 12  hum         17379 non-null  float64
 13  windspeed   17379 non-null  float64
 14  casual      17379 non-null  int64
 15  registered  17379 non-null  int64
 16  cnt         17379 non-null  int64
dtypes: float64(4), int64(12), str(1)
memory usage: 2.4 MB

None

In [63]:
#inspeção#

# caracteristica da base de dados - descrições

display(df_hour.describe()) # descrição/resumo estatistico

,instant,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
count,17379.0000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000
mean,8690.0000,2.501640,0.502561,6.537775,11.546752,0.028770,3.003683,0.682721,1.425283,0.496987,0.475775,0.627229,0.190098,35.676218,153.786869,189.463088
std,5017.0295,1.106918,0.500008,3.438776,6.914405,0.167165,2.005771,0.465431,0.639357,0.192556,0.171850,0.192930,0.122340,49.305030,151.357286,181.387599
min,1.0000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.020000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,4345.5000,2.000000,0.000000,4.000000,6.000000,0.000000,1.000000,0.000000,1.000000,0.340000,0.333300,0.480000,0.104500,4.000000,34.000000,40.000000
50%,8690.0000,3.000000,1.000000,7.000000,12.000000,0.000000,3.000000,1.000000,1.000000,0.500000,0.484800,0.630000,0.194000,17.000000,115.000000,142.000000
75%,13034.5000,3.000000,1.000000,10.000000,18.000000,0.000000,5.000000,1.000000,2.000000,0.660000,0.621200,0.780000,0.253700,48.000000,220.000000,281.000000
max,17379.0000,4.000000,1.000000,12.000000,23.000000,1.000000,6.000000,1.000000,4.000000,1.000000,1.000000,1.000000,0.850700,367.000000,886.000000,977.000000

In [64]:
# tratamento de dados

# colunas - Nos seu arquivos, não excluimos colunas

# nulos - Nos seu arquivos, não encontramos valores nulos. Após a verificação das variáveis, não foram identificados valores ausentes no dataset. Dessa forma, não foi necessário realizar tratamento ou exclusão de registros por ausência de dados.

# tipos de variaveis - Nos seu arquivos, as variaveis estão corretas.

# duplicados # A análise identificou 0 registros duplicados, não sendo necessário realizar a remoção de duplicidades.

df_hour.duplicated().sum()

np.int64(0)

In [65]:
# tratamento de dados

# valores distintos

df_hour.nunique()

instant       17379
dteday          731
season            4
yr                2
mnth             12
hr               24
holiday           2
weekday           7
workingday        2
weathersit        4
temp             50
atemp            65
hum              89
windspeed        30
casual          322
registered      776
cnt             869
dtype: int64

In [66]:
# Descrição dass variaveis

#| Coluna       | Significado                     | Tipo de informação  |
#| ------------ | ------------------------------- | ------------------- |
#| `instant`    | número sequencial do registro   | identificador       |
#| `dteday`     | data                            | data                |
#| `season`     | estação do ano                  | categórica          |
#| `yr`         | ano                             | categórica          |
#| `mnth`       | mês                             | categórica/temporal |
#| `hr`         | hora do dia                     | temporal            |
#| `holiday`    | feriado ou não                  | categórica          |
#| `weekday`    | dia da semana                   | categórica          |
#| `workingday` | dia de trabalho ou não          | categórica          |
#| `weathersit` | condição climática              | categórica          |
#| `temp`       | temperatura normalizada         | quantitativa        |
#| `atemp`      | sensação térmica normalizada    | quantitativa        |
#| `hum`        | umidade normalizada             | quantitativa        |
#| `windspeed`  | velocidade do vento normalizada | quantitativa        |
#| `casual`     | usuários ocasionais             | quantitativa        |
#| `registered` | usuários registrados            | quantitativa        |
#| `cnt`        | total de bicicletas alugadas    | quantitativa        |

In [67]:
# A coluna season usa códigos para as estações do ano

df_hour['season'].unique()

array([1, 2, 3, 4])

In [68]:
#Quantas vezes aparece na tabela as esatçoes do ano

df_hour['season'].value_counts().sort_index()

season
1    4242
2    4409
3    4496
4    4232
Name: count, dtype: int64

In [69]:
# Criar nova coluna season_nome

df_hour['season_nome'] = df_hour['season'].map({
    1: 'Primavera',
    2: 'Verão',
    3: 'Outono',
    4: 'Inverno'})

display(df_hour)

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt,season_nome
0,1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0000,3,13,16,Primavera
1,2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0000,8,32,40,Primavera
2,3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0000,5,27,32,Primavera
3,4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0000,3,10,13,Primavera
4,5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0000,0,1,1,Primavera
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17374,17375,2012-12-31,1,1,12,19,0,1,1,2,0.26,0.2576,0.60,0.1642,11,108,119,Primavera
17375,17376,2012-12-31,1,1,12,20,0,1,1,2,0.26,0.2576,0.60,0.1642,8,81,89,Primavera
17376,17377,2012-12-31,1,1,12,21,0,1,1,1,0.26,0.2576,0.60,0.1642,7,83,90,Primavera
17377,17378,2012-12-31,1,1,12,22,0,1,1,1,0.26,0.2727,0.56,0.1343,13,48,61,Primavera
17378,17379,2012-12-31,1,1,12,23,0,1,1,1,0.26,0.2727,0.65,0.1343,12,37,49,Primavera

In [70]:
# A coluna yr usa códigos para codificar o ano

df_hour['yr'].value_counts().sort_index()

yr
0    8645
1    8734
Name: count, dtype: int64

In [71]:
# Criar nova coluna ano

df_hour['ano'] = df_hour['yr'].map({
    0: 2011,
    1: 2012
})

display(df_hour)

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt,season_nome,ano
0,1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0000,3,13,16,Primavera,2011
1,2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0000,8,32,40,Primavera,2011
2,3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0000,5,27,32,Primavera,2011
3,4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0000,3,10,13,Primavera,2011
4,5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0000,0,1,1,Primavera,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17374,17375,2012-12-31,1,1,12,19,0,1,1,2,0.26,0.2576,0.60,0.1642,11,108,119,Primavera,2012
17375,17376,2012-12-31,1,1,12,20,0,1,1,2,0.26,0.2576,0.60,0.1642,8,81,89,Primavera,2012
17376,17377,2012-12-31,1,1,12,21,0,1,1,1,0.26,0.2576,0.60,0.1642,7,83,90,Primavera,2012
17377,17378,2012-12-31,1,1,12,22,0,1,1,1,0.26,0.2727,0.56,0.1343,13,48,61,Primavera,2012
17378,17379,2012-12-31,1,1,12,23,0,1,1,1,0.26,0.2727,0.65,0.1343,12,37,49,Primavera,2012

In [72]:

# A coluna mnth usa códigos para codificar o mês

df_hour['mes_nome'] = df_hour['mnth'].map({
    1: 'Janeiro',
    2: 'Fevereiro',
    3: 'Março',
    4: 'Abril',
    5: 'Maio',
    6: 'Junho',
    7: 'Julho',
    8: 'Agosto',
    9: 'Setembro',
    10: 'Outubro',
    11: 'Novembro',
    12: 'Dezembro'
})

display(df_hour)

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt,season_nome,ano,mes_nome
0,1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0000,3,13,16,Primavera,2011,Janeiro
1,2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0000,8,32,40,Primavera,2011,Janeiro
2,3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0000,5,27,32,Primavera,2011,Janeiro
3,4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0000,3,10,13,Primavera,2011,Janeiro
4,5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0000,0,1,1,Primavera,2011,Janeiro
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17374,17375,2012-12-31,1,1,12,19,0,1,1,2,0.26,0.2576,0.60,0.1642,11,108,119,Primavera,2012,Dezembro
17375,17376,2012-12-31,1,1,12,20,0,1,1,2,0.26,0.2576,0.60,0.1642,8,81,89,Primavera,2012,Dezembro
17376,17377,2012-12-31,1,1,12,21,0,1,1,1,0.26,0.2576,0.60,0.1642,7,83,90,Primavera,2012,Dezembro
17377,17378,2012-12-31,1,1,12,22,0,1,1,1,0.26,0.2727,0.56,0.1343,13,48,61,Primavera,2012,Dezembro
17378,17379,2012-12-31,1,1,12,23,0,1,1,1,0.26,0.2727,0.65,0.1343,12,37,49,Primavera,2012,Dezembro

In [73]:
# a variável workingday considera se é dia útil ou não útil

df_hour['tipo_dia'] = df_hour['workingday'].map({
    0: 'Não útil',
    1: 'Dia útil'
})

display(df_hour)

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,...,atemp,hum,windspeed,casual,registered,cnt,season_nome,ano,mes_nome,tipo_dia
0,1,2011-01-01,1,0,1,0,0,6,0,1,...,0.2879,0.81,0.0000,3,13,16,Primavera,2011,Janeiro,Não útil
1,2,2011-01-01,1,0,1,1,0,6,0,1,...,0.2727,0.80,0.0000,8,32,40,Primavera,2011,Janeiro,Não útil
2,3,2011-01-01,1,0,1,2,0,6,0,1,...,0.2727,0.80,0.0000,5,27,32,Primavera,2011,Janeiro,Não útil
3,4,2011-01-01,1,0,1,3,0,6,0,1,...,0.2879,0.75,0.0000,3,10,13,Primavera,2011,Janeiro,Não útil
4,5,2011-01-01,1,0,1,4,0,6,0,1,...,0.2879,0.75,0.0000,0,1,1,Primavera,2011,Janeiro,Não útil
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17374,17375,2012-12-31,1,1,12,19,0,1,1,2,...,0.2576,0.60,0.1642,11,108,119,Primavera,2012,Dezembro,Dia útil
17375,17376,2012-12-31,1,1,12,20,0,1,1,2,...,0.2576,0.60,0.1642,8,81,89,Primavera,2012,Dezembro,Dia útil
17376,17377,2012-12-31,1,1,12,21,0,1,1,1,...,0.2576,0.60,0.1642,7,83,90,Primavera,2012,Dezembro,Dia útil
17377,17378,2012-12-31,1,1,12,22,0,1,1,1,...,0.2727,0.56,0.1343,13,48,61,Primavera,2012,Dezembro,Dia útil
17378,17379,2012-12-31,1,1,12,23,0,1,1,1,...,0.2727,0.65,0.1343,12,37,49,Primavera,2012,Dezembro,Dia útil

In [74]:
# condificação das condiçôes climaticas

df_hour['weathersit'].value_counts().sort_index()

weathersit
1    11413
2     4544
3     1419
4        3
Name: count, dtype: int64

In [32]:
# Criar a coluna clima

df_hour['clima'] = df_hour['weathersit'].map({
    1: 'Poucas nuvens/Céu limpo',
    2: 'Nublado/Névoa',
    3: 'Chuva leve/Neve',
    4: 'Chuva forte'
})

display(df_hour)

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,...,hum,windspeed,casual,registered,cnt,season_nome,ano,mes_nome,tipo_dia,clima
0,1,2011-01-01,1,0,1,0,0,6,0,1,...,0.81,0.0000,3,13,16,Primavera,2011,Janeiro,Não útil,Poucas nuvens/Céu limpo
1,2,2011-01-01,1,0,1,1,0,6,0,1,...,0.80,0.0000,8,32,40,Primavera,2011,Janeiro,Não útil,Poucas nuvens/Céu limpo
2,3,2011-01-01,1,0,1,2,0,6,0,1,...,0.80,0.0000,5,27,32,Primavera,2011,Janeiro,Não útil,Poucas nuvens/Céu limpo
3,4,2011-01-01,1,0,1,3,0,6,0,1,...,0.75,0.0000,3,10,13,Primavera,2011,Janeiro,Não útil,Poucas nuvens/Céu limpo
4,5,2011-01-01,1,0,1,4,0,6,0,1,...,0.75,0.0000,0,1,1,Primavera,2011,Janeiro,Não útil,Poucas nuvens/Céu limpo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17374,17375,2012-12-31,1,1,12,19,0,1,1,2,...,0.60,0.1642,11,108,119,Primavera,2012,Dezembro,Dia útil,Nublado/Névoa
17375,17376,2012-12-31,1,1,12,20,0,1,1,2,...,0.60,0.1642,8,81,89,Primavera,2012,Dezembro,Dia útil,Nublado/Névoa
17376,17377,2012-12-31,1,1,12,21,0,1,1,1,...,0.60,0.1642,7,83,90,Primavera,2012,Dezembro,Dia útil,Poucas nuvens/Céu limpo
17377,17378,2012-12-31,1,1,12,22,0,1,1,1,...,0.56,0.1343,13,48,61,Primavera,2012,Dezembro,Dia útil,Poucas nuvens/Céu limpo
17378,17379,2012-12-31,1,1,12,23,0,1,1,1,...,0.65,0.1343,12,37,49,Primavera,2012,Dezembro,Dia útil,Poucas nuvens/Céu limpo

In [ ]:
# Pergunta 1: Qual foi a quantidade média de bicicletas alugadas por hora em cada ano?

media_por_ano = (
    df_hour.groupby('ano')['cnt']
    .mean()
    .round(2)
)

display(media_por_ano)

diferenca = media_por_ano.loc[2012] - media_por_ano.loc[2011]

display (diferenca)

resposta1 = "Resposta:Em 2011, a quantidade média de bicicletas alugadas foi de 143,79 por hora, enquanto em 2012 foi de 234,67 por hora. Portanto, houve um aumento de 90,88 bicicletas na média de aluguéis por hora entre os dois anos."

print(resposta1)

ano
2011    143.79
2012    234.67
Name: cnt, dtype: float64

np.float64(90.88)

Resposta:Em 2011, a quantidade média de bicicletas alugadas foi de 143,79 por hora, enquanto em 2012 foi de 234,67 por hora. Portanto, houve um aumento de 90,88 bicicletas na média de aluguéis por hora entre os dois anos.

In [ ]:
# Pergunta 2: Em qual horário do dia ocorreu a maior média de bicicletas alugadas?

media_por_hora = (
    df_hour.groupby('hr')['cnt']
    .mean()
    .round(2)
)

display (media_por_hora)

horario_maior_media = media_por_hora.idxmax()
maior_media = media_por_hora.max()

print("Horário com maior média:", horario_maior_media, "horas")
print("Média de bicicletas alugadas:", maior_media)

resposta2 = "Resposta: O horário com a maior média de bicicletas alugadas foi 17h, com aproximadamente 461,45 bicicletas por hora. Também foram observadas médias elevadas às 18h e às 8h. Esses resultados mostram uma maior concentração de aluguéis em determinados horários do dia."

print(resposta2)

hr
0      53.90
1      33.38
2      22.87
3      11.73
4       6.35
5      19.89
6      76.04
7     212.06
8     359.01
9     219.31
10    173.67
11    208.14
12    253.32
13    253.66
14    240.95
15    251.23
16    311.98
17    461.45
18    425.51
19    311.52
20    226.03
21    172.31
22    131.34
23     87.83
Name: cnt, dtype: float64

Horário com maior média: 17 horas
Média de bicicletas alugadas: 461.45
Resposta: O horário com a maior média de bicicletas alugadas foi 17h, com aproximadamente 461,45 bicicletas por hora. Também foram observadas médias elevadas às 18h e às 8h. Esses resultados mostram uma maior concentração de aluguéis em determinados horários do dia.

In [87]:
# Pergunta 3: Qual mês apresentou a maior média de bicicletas alugadas por hora?

media_por_mes = (
    df_hour.groupby('mes_nome')['cnt']
    .mean()
    .round(2)
    .sort_values(ascending=False)
)
display (media_por_mes)


Resposta3 = "O mês que apresentou a maior média de bicicletas alugadas por hora foi setembro, com aproximadamente 240,77 bicicletas por hora."

print(Resposta3)

mes_nome
Setembro     240.77
Junho        240.52
Agosto       238.10
Julho        231.82
Maio         222.91
Outubro      222.16
Abril        187.26
Novembro     177.34
Março        155.41
Dezembro     142.30
Fevereiro    112.87
Janeiro       94.42
Name: cnt, dtype: float64

O mês que apresentou a maior média de bicicletas alugadas por hora foi setembro, com aproximadamente 240,77 bicicletas por hora.

In [90]:
# Pergunta 4: A média de bicicletas alugadas é maior nos dias úteis ou nos dias não úteis?

media_tipo_dia = (
    df_hour.groupby('tipo_dia')['cnt']
    .mean()
    .round(2)
    .sort_values(ascending=False)
)

display(media_tipo_dia)



Resposta4 = "A média de bicicletas alugadas foi maior nos dias úteis, com aproximadamente 193,21 bicicletas por hora"
print(Resposta4)

tipo_dia
Dia útil    193.21
Não útil    181.41
Name: cnt, dtype: float64

A média de bicicletas alugadas foi maior nos dias úteis, com aproximadamente 193,21 bicicletas por hora

In [ ]:
# Pergunta 5: Em quais horários do dia os usuários ocasionais e registrados apresentam a maior quantidade total de aluguéis? Informe o horario de pico para cada classe de usuário

alugueis_por_hora_usuario = (
    df_hour.groupby('hr')[['casual', 'registered']]
    .sum()
    
)

print(alugueis_por_hora_usuario)

hora_pico_casual = alugueis_por_hora_usuario['casual'].idxmax()
hora_pico_registrado = alugueis_por_hora_usuario['registered'].idxmax()

print("Horário de pico dos usuários casuais:", hora_pico_casual, "horas")
print("Horário de pico dos usuários registrados:", hora_pico_registrado, "horas")

Resposta5 = " Os usuários casuais tem horario de pico as 14:00 h e os usuários registrados as 17:00 h."

    casual  registered
hr
0     7375       31755
1     4709       19455
2     3412       12940
3     1893        6281
4      874        3554
5     1012       13249
6     3017       52115
7     8037      146134
8    15761      245240
9    22458      136980
10   33789       92468
11   43286      108034
12   49718      134696
13   52713      132206
14   55089      120563
15   54606      128543
16   53834      173914
17   54220      282640
18   44496      265276
19   35505      191284
20   26378      138172
21   20570      104875
22   16200       79412
23   11065       52876
Horário de pico dos usuários casuais: 14 h
Horário de pico dos usuários registrados: 17 h